In [ ]:
import pandas as pd
from datetime import date
import json

 ## appending annotated jsonl batches to get full annotated data

In [ ]:
df_annotated_til_20240531 = pd.read_json('../backend/data/annotations/until_20240531_annotations.jsonl', lines=True)
batches_list = [
    df_annotated_til_20240531
]
df_full_annotations = pd.DataFrame()
for batch in batches_list:
    df_full_annotations = pd.concat([df_full_annotations, batch], ignore_index=True)
df_full_annotations.drop_duplicates(subset=['date'], inplace=True, keep='last')
df_full_annotations

           date  working  total_points  start_point  end_point
0    2014-06-01    False             1          NaN        NaN
1    2014-06-04    False             1          NaN        NaN
2    2014-06-06    False            13          NaN        NaN
3    2014-06-09    False             1          NaN        NaN
4    2014-06-11    False             1          NaN        NaN
...         ...      ...           ...          ...        ...
3374 2024-05-26    False            46          NaN        NaN
3375 2024-05-27    False            47          NaN        NaN
3376 2024-05-28    False            33          NaN        NaN
3377 2024-05-29    False             1          NaN        NaN
3378 2024-05-31    False            40          NaN        NaN

[3205 rows x 5 columns]

In [ ]:
df_full_annotations.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3205 entries, 0 to 3378
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          3205 non-null   datetime64[ns]
 1   working       3205 non-null   bool
 2   total_points  3205 non-null   int64
 3   start_point   2450 non-null   float64
 4   end_point     2450 non-null   float64
dtypes: bool(1), datetime64[ns](1), float64(2), int64(1)
memory usage: 128.3 KB

In [ ]:
df_full_annotations.describe(include='all').T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
date,3205,NaN,NaN,NaN,2019-09-10 13:00:25.834633472,2014-06-01 00:00:00,2017-05-26 00:00:00,2019-09-26 00:00:00,2022-02-27 00:00:00,2024-05-31 00:00:00,NaN
working,3205,2,True,2450,NaN,NaN,NaN,NaN,NaN,NaN,NaN
total_points,3205.0,NaN,NaN,NaN,61.825585,0.0,22.0,54.0,89.0,325.0,49.391628
start_point,2450.0,NaN,NaN,NaN,4.335102,0.0,0.0,0.0,2.0,105.0,9.483774
end_point,2450.0,NaN,NaN,NaN,68.292245,0.0,35.0,60.0,93.0,324.0,46.907495

 ## generating all visits groutes by day

In [ ]:
file = "../backend/data/visitas_business_days_by_day.json"
dict_visits_business_days_by_day = json.load(open(file, 'r'))
dict_visits_business_days_by_day['2018-06-15']

{'data': [{'place': 'Calle 151, Tibabuyes, UPZs de Bogotá, Localidad Suba, Bogotá, Bogotá Distrito Capital - Municipio, Bogotá, Distrito Capital, RAP (Especial) Central, 111161, Colombia',
   'timestamp': '2018-06-15 10:05:00',
   'latitude': 4.7535113,
   'longitude': -74.1021358}],
 'business_day': False}

 ## adding the start and end timestamps to the annotations dataframe

In [ ]:
df_final_contract = df_full_annotations[df_full_annotations['working']].copy()
df_final_contract.reset_index(inplace=True)
df_final_contract['index'] = df_final_contract.index
df_final_contract['start_timestamp'] = None
df_final_contract['end_timestamp'] = None
df_final_contract

,index,date,working,total_points,start_point,end_point,start_timestamp,end_timestamp
0,0,2014-06-16,True,8,3.0,6.0,None,None
1,1,2014-06-17,True,3,0.0,2.0,None,None
2,2,2014-06-19,True,4,0.0,3.0,None,None
3,3,2014-06-20,True,19,1.0,14.0,None,None
4,4,2014-06-21,True,29,0.0,25.0,None,None
...,...,...,...,...,...,...,...,...
2445,2445,2024-04-23,True,52,0.0,51.0,None,None
2446,2446,2024-04-24,True,52,0.0,51.0,None,None
2447,2447,2024-04-26,True,57,0.0,56.0,None,None
2448,2448,2024-04-27,True,47,0.0,46.0,None,None
2449,2449,2024-05-09,True,36,0.0,35.0,None,None

In [ ]:
for _, day in df_final_contract.iterrows():
    date_str = str(day.date.strftime('%Y-%m-%d'))
    df_final_contract.loc[day['index'], 'start_timestamp'] = dict_visits_business_days_by_day[date_str]['data'][int(day.start_point)]['timestamp']
    df_final_contract.loc[day['index'], 'end_timestamp'] = dict_visits_business_days_by_day[date_str]['data'][int(day.end_point)]['timestamp']

In [ ]:
df_final_contract = df_final_contract.drop(columns=['index', 'working', 'start_point', 'end_point', 'total_points'])
df_final_contract

           date      start_timestamp        end_timestamp
0    2014-06-16  2014-06-16 11:23:00  2014-06-16 22:10:00
1    2014-06-17  2014-06-17 11:26:00  2014-06-17 22:09:00
2    2014-06-19  2014-06-19 07:23:00  2014-06-19 17:55:00
3    2014-06-20  2014-06-20 07:48:00  2014-06-20 20:11:00
4    2014-06-21  2014-06-21 05:24:00  2014-06-21 16:29:00
...         ...                  ...                  ...
2445 2024-04-23  2024-04-23 08:39:00  2024-04-23 17:04:00
2446 2024-04-24  2024-04-24 08:48:00  2024-04-24 14:13:00
2447 2024-04-26  2024-04-26 10:09:00  2024-04-26 18:12:00
2448 2024-04-27  2024-04-27 09:08:00  2024-04-27 13:02:00
2449 2024-05-09  2024-05-09 09:28:00  2024-05-09 18:40:00

[2450 rows x 3 columns]

 ## generating final contract

In [ ]:
df_final_contract.to_csv('../backend/data/final_contract.csv', index=False)